# Generated by Django 5.2.5 on 2025-09-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_planned_pieces', models.IntegerField()),
                ('total_actual_pieces', models.IntegerField()),
                ('total_downtime_minutes', models.IntegerField()),
                ('total_defects', models.IntegerField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
                ('oee_percentage', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cell')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.defect')),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.downtime')),
                ('planned_downtime_cells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planneddowntimecells')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.production')),
            ],
            options={
                'verbose_name_plural': 'Recaps',
            },
        ),
        migrations.CreateModel(
            name='OEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cell')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.recap')),
            ],
            options={
                'verbose_name_plural': 'Historial OEE',
            },
        ),
    ]
