# Generated by Django 5.2.5 on 2025-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_recap_defect_remove_recap_downtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recap',
            name='planned_downtime_cells',
        ),
    ]
