# Generated by Django 5.2.5 on 2025-09-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recap',
            name='defect',
        ),
        migrations.RemoveField(
            model_name='recap',
            name='downtime',
        ),
        migrations.RemoveField(
            model_name='recap',
            name='production',
        ),
    ]
