# Generated by Django 5.2.5 on 2025-09-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('planning', '0004_remove_plannedproduction_unique_workorder_per_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='hourlyproduction',
            unique_together={('hour', 'production_detail')},
        ),
    ]
