# Generated by Django 5.2.5 on 2025-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_remove_defect_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyproduction',
            name='hour',
            field=models.IntegerField(choices=[('7:00', '7:00'), ('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')]),
        ),
    ]
