# Generated by Django 5.2.5 on 2025-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_hourlyproduction_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyproduction',
            name='hour',
            field=models.IntegerField(choices=[('7', '7:00'), ('8', '8:00'), ('9', '9:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00')]),
        ),
    ]
