# Generated by Django 5.2.5 on 2025-09-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_alter_hourlyproduction_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='cycle',
        ),
    ]
