# Generated by Django 5.2.5 on 2025-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
