# Generated by Django 5.2.5 on 2025-09-03 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('planning', '0002_productiondetail_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plannedproduction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='plannedproduction',
            constraint=models.UniqueConstraint(fields=('date', 'workorder'), name='unique_workorder_per_date'),
        ),
    ]
