# Generated by Django 5.2.5 on 2025-09-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_plannedproduction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedproduction',
            name='unique_workorder_per_date',
        ),
    ]
