# Generated by Django 5.2.5 on 2025-09-26 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_remove_production_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
