# Generated by Django 5.2.5 on 2025-09-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_downtime_created_at_hourlyproduction_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='production_detail',
        ),
    ]
