# Generated by Django 5.2.5 on 2025-09-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('manufacturing', '0009_remove_downtime_production_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cell'),
        ),
    ]
